---
executor: "KubernetesExecutor"
logs:
  persistence:
    enabled: true
    existingClaim: airflow-log
dags:
  gitSync:
    enabled: true
    repo: https://github.com/ankiyong/airflow_dag.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    period: 5s
    credentialsSecret: git-credentials
    sshKeySecret: airflow-ssh-secret
    containerName: git-sync
    uid: 65533
