---
executor: "KubernetesExecutor"
webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080
logs:
  persistence:
    enabled: true
    existingClaim: airflow-log-pvc
dags:
  gitSync:
    enabled: true
    repo: https://github.com/ankiyong/data_streaming.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    period: 5s
    credentialsSecret: git-credentials
    sshKeySecret: airflow-git-ssh-secret
    containerName: git-sync
    uid: 65533
ingress:
  enabled: true
  web:
    enabled: true
    annotations: 
      ingress.kubernetes.io/rewrite-target: /
    path: "/airflow"
    pathType: "prefix"
    host: "aky.dev"
    hosts: []
    ingressClassName: "nginx"
    tls:
      enabled: false
      secretName: ""
