---
executor: "KubernetesExecutor"
logs:
  persistence:
    enabled: true
    existingClaim: airflow-log-pvc
dags:
  gitSync:
    enabled: true
    repo: https://github.com/ankiyong/data_streaming.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    period: 5s
    credentialsSecret: git-credentials
    sshKeySecret: airflow-git-ssh-secret
    containerName: git-sync
    uid: 65533

airflow:
  config: 
    AIRFLOW__WEBSERVER__BASE_URL: "http://aky.dev/airflow/"

ingress:
  apiVersion: networking.k8s.io/v1

  web:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    enabled: true
    host: "aky.dev"
    path: "/airflow"
    ingressClassName: "nginx"
