apiVersion: v1
kind: PersistentVolume
metadata:
 name: airflow-log-pv
spec:
 storageClassName: local-storage
 capacity:
  storage: 10Gi
 accessModes:
  - ReadWriteMany
 hostPath:
  path: "/root/pvc/olist/airflow/logs"