apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-log
  namespace: airflow
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G