apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Python
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  pythonFile: local:///opt/spark/read_json.py
  arguments:
  - "5000"
  sparkVersion: 3.5.3
  driver:
    labels:
      version: 3.5.3
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    labels:
      version: 3.5.3
    instances: 1
    cores: 1
    memory: 512m
    volumeMounts:
      - name: airflow-log-pvc
        mountPath: /mnt/spark/data
