apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    minExecutors: 2
    maxExecutors: 10
  sparkConf:
    spark.jars.ivy: "/tmp/ivy"
    spark.jars.repositories: "https://mvnrepository.com/artifact/org.postgresql/postgresql"
    spark.jars.packages: "org.postgresql:postgresql:42.7.5"
  timeToLiveSeconds: 60
  type: Python
  mode: cluster
  image: pop2413/spark:1.5
  imagePullPolicy: IfNotPresent
  # imagePullSecrets:
  #   - name: docker-hub
  mainApplicationFile: local:///opt/spark/jobs/read_json.py
  sparkVersion: 3.5.3
  volumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data
    - name: spark-jobs
      persistentVolumeClaim:
        claimName: spark-jobs
    # - name: spark-jobs
    #   hostPath:
    #     path: /root/pvc/olist/spark/jobs
    # - name: data
    #   hostPath:
    #     path: /root/pvc/olist/spark/data
  driver:
    labels:
      version: 3.5.3
    cores: 1
    coreLimit: 1000m
    memory: 512m
    serviceAccount: spark
    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs
      - name: data
        mountPath: /opt/spark/data
  executor:
    labels:
      version: 3.5.3
    instances: 2
    cores: 1
    coreLimit: 1000m
    memory: 512m
    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs
      - name: data
        mountPath: /opt/spark/data
