apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  timeToLiveSeconds: 60 # Completed 상태의 pod를 60초 후에 삭제
  type: Scala
  mode: cluster
  image: localhost:5000/spark:1.0 # 사용하는 이미지
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/jobs/read_json.py # 이미지 내의 jar 파일
  sparkVersion: 3.5.0
  driver:
    labels:
      version: 3.5.0
    cores: 1
    coreLimit: 1000m
    memory: 512m
    serviceAccount: spark # 서비스 어카운트
  executor:
    labels:
      version: 3.5.0
    instances: 2 # executor의 수
    cores: 1 # cpu requests
    coreLimit: 1000m # cpu limit
    memory: 512m
    volumeMounts:
      - name: airflow-log-pvc
        mountPath: /opt/spark/jobs
