apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-process
  namespace: default
spec:
  type: Python
  mode: cluster
  image: localhost:5000/pyspark-on-k8s:1.0
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  arguments:
  - "5000"
  sparkVersion: 3.5.4
  driver:
    labels:
      version: 3.5.4
    cores: 1
    memory: 512m
    serviceAccount: spark
  executor:
    instances: 1
    cores: 1
    memory: 512m
