apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk
spec:
  version: 8.14.3
  nodeSets:
  - name: node
    count: 3
    config:
      node.store.allow_mmap: false
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: http
          port: 9200
          targetPort: 9200
          nodePort: 30920