apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - name: http
      nodePort: 30800
      port: 8000
      targetPort: 8000
      protocol: TCP