name: git to gcs
on:
  push:
    path:
    - 'static_data/**'
    branches:
    - main
jobs:
  deploy-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all git history
      run: |
        git fetch --prune --unshallow
    - name: Check if there are any changes in static_data
      run: |
        if git diff --quiet HEAD~1 HEAD -- static_data/; then
            echo "No changes in static_data, skipping rsync."
          exit 0
          echo "Changes detected in static_data, proceeding with rsync."
        fi
    - id: 'auth'
      if: success()
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
        project_id: '${{ secrets.PROJECT_ID }}'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '${{ secrets.CSV_PATH }}'
        destination: '${{ secrets.BUCKET_NAME }}'
