name: git to gcs

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - id: gcp_auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v4

    - name: Deploy
      run: |-
        gsutil cp -R /home/runner/work/data_streaming/data_streaming/static_data gs://olist_data_buckets
