name: git to gcs
on:
  push:
    branches:
    - main
jobs:
  deploy-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/95468451293/locations/global/workloadIdentityPools/github/providers/olist'
        service_account: 'olist-dev'
        project_id: 'olist-data-engineering'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'static_data'
        destination: 'olist_data_buckets'


# on:
#   push:
#     branches:
#     - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - id: gcp_auth
#       uses: google-github-actions/auth@v2
#       with:
#         credentials_json: '${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}'
#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@v2

#     - name: Deploy
#       run: |-
#         gsutil -m rsync -r /home/runner/work/data_streaming/data_streaming gs://olist_data_buckets/
