name: git to gcs

on:
  push:
    branches:
    - main
jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/95468451293/locations/global/workloadIdentityPools/github-action/'
        service_account: 'aky-dev@olist-data-engineering.iam.gserviceaccount.com'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: './static_data'
        destination: 'olist_data_buckets'
