name: git to gcs
on:
  push:
    path:
    - 'static_data/**'
    branches:
    - main
jobs:
  deploy-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch all git history
      run: |
        git fetch --prune --unshallow
    - name: Check if there are any changes in static_data
      run: |
        if git diff --quiet HEAD~1 HEAD -- static_data/; then
            echo "No changes in static_data, skipping rsync."
          exit 1
          echo "Changes detected in static_data, proceeding with rsync."
        fi
    - uses: 'actions/checkout@v2'
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'static_data'
        destination: 'olist_data_buckets'
    - name: Load CSV to BigQuery
      run: |
        for file in static_data/*.csv; do
          filename=$(basename "$file" .csv)
          echo "Uploading $file to BigQuery table $filename..."
          echo 
          bq load \
            --source_format=CSV \
            --autodetect \
            --replace \
            olist_dataset.$filename \
            gs://${{ secrets.BUCKET_NAME }}/static_data/$filename.csv
          echo "$file uploaded successfully!"
        done