name: git to gcs
on:
  push:
    path:
    - 'static_data/**'
    branches:
    - main
jobs:
  deploy-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'static_data'
        destination: 'olist_data_buckets'
    - name: Load CSV to BigQuery
      run: |
        for file in static_data/*.csv; do
          filename=$(basename "$file" .csv)
          echo "Uploading $file to BigQuery table $filename..."

          bq load \
            --source_format=CSV \
            --autodetect \
            --replace \
            ${{ secrets.BIGQUERY_DATASET }}.$file \
            gs://${{ secrets.BUCKET_NAME }}/static_data/$filename.csv
          echo "$file uploaded successfully!"
        done