name: git to gcs

on:
  push:
    branches:
    - main
jobs:
  deploy-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/95468451293/locations/global/workloadIdentityPools/github-action/'
        service_account: 'aky-dev@olist-data-engineering.iam.gserviceaccount.com'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'static_data'
        destination: 'olist_data_buckets'
