name: git to gcs

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.4
      with:
        service_account_key: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCS_PROJECT_ID }}
        export_default_credentials: true
    - name: Deploy
      if: env.CSV_CHANGED == 'true'
      run: |-
        gsutil -m rsync -R /home/aky/projects/olist/static_data gs://olist_data_buckets/
